### ISSUE TITLE
Please provide `modelscope_studio.__version__` so we can check the version.

### ISSUE THREAD

**Issue by JianxinMa** [modelscope/modelscope-studio#21]
We would like to check the version of modelscope_studio in our code, as we find that the older versions have some glitches when running with the latest version of gradio. The latest version of modelscope_studio works perfectly, though.

**Comment by Col0ring** [comment]
Yep! we will provide this property from next version. And for now, you could use `hasattr(mgr, 'Flow')` to check the latest version.
