### ISSUE TITLE
ImportError: cannot import name 'encode_image' from 'modelscope_studio'

### ISSUE THREAD

**Issue by sankexin** [modelscope/modelscope-studio#28]
Ubuntu

ImportError: cannot import name 'encode_image' from 'modelscope_studio' (/opt/conda/lib/python3.10/site-packages/modelscope_studio/__init__.py)

**Comment by Col0ring** [comment]
modelscope-studio 本身没有导出这类方法，你应该是依赖了另一个同名的包：https://developer.aliyun.com/ask/476896
