### ISSUE TITLE
加入examples = gr.Examples()后chat_bot =  mgr.Chatbot()对话框无法上下滚动了

### ISSUE THREAD

**Issue by Note-Liu** [modelscope/modelscope-studio#43]

**Comment by Col0ring** [comment]
mgr.Chatbot 应该是不支持 examples 的，有具体的代码示例吗

**Comment by Note-Liu** [comment]
import gradio as gr
import io
import os
import copy

import modelscope_studio as mgr
from io import BytesIO

model_name = "Test"
ERROR_MSG = "Error, please retry"

def respond(_question, _chat_bot, _app_cfg):
    _answer = "床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。"
    _chat_bot.append((_question,_answer))
    
    return  gr.MultimodalTextbox(
            interactive=True,
            file_types=["image"],
            placeholder="Enter message or upload file...",
            show_label=False,
            file_count="multiple"
        ), _chat_bot, _app_cfg
  

def clear(txt_message, app_session):
    print("Clear")
    txt_message.clear()
    app_session['sts'] = None
    app_session['ctx'] = []
    new_chat_bot_value = []
    return gr.MultimodalTextbox(value=None, interactive=True), gr.Chatbot(value=new_chat_bot_value) , app_session


block_css = """
.gradio-container {margin: 0.1% 1% 0 1% !important; max-width: 98% !important;};
#buttons button {
    min-width: min(120px,100%);
}

.gradient-text {
    font-size: 28px;
    width: auto;
    font-weight: bold;
    background: linear-gradient(45deg, red, orange, yellow, green, blue, indigo, violet);
    background-clip: text;
    -webkit-background-clip: text;
    color: transparent;
}

.plain-text {
    font-size: 22px;
    width: auto;
    font-weight: bold;
}
"""
init_conversation = [
    [
        None,
        {
            "text": "Talk to me now",
            "flushing": False
        }
    ],
]

txt_message = gr.MultimodalTextbox(
    interactive=True,
    file_types=["image"],
    placeholder="Enter message ...",
    show_label=False,
    file_count="multiple"
)

with gr.Blocks(css=block_css) as demo: 
    with gr.Tab(model_name):  
        with gr.Row():
            # 左侧列内容
            with gr.Column(scale=2):
                examples = gr.Examples(
                    examples=[
                            [{"files": ["data/001.png"], "text":"描述一下图片"}],
                            [{"files": ["data/002.png"], "text": "描述一下图片"}],
                            [{"files": ["data/003.png"], "text": "描述一下图片"}],
                            [{"files": ["data/004.png"], "text": "描述一下图片"}],
                            ],
                    inputs=[txt_message]
                    )

            with gr.Column(scale = 8):
                app_session = gr.State({'sts': None, 'ctx': [], 'images_cnt': 0, 'chat_type': 'Chat'}) 
                 
                chat_bot =  mgr.Chatbot(label=f"Chat with {model_name}", value=copy.deepcopy(init_conversation), height=600, flushing=False, bubble_full_width=False)
                 
                with gr.Row():
                    with gr.Column(scale=8):
                        txt_message.render()
                    submit_btn = gr.Button(value="Submit", variant="primary")
                    clear_button = gr.Button(value='Clear', interactive=True)
                    
                    txt_message.submit(
                        respond,
                        [txt_message, chat_bot, app_session],
                        [txt_message, chat_bot, app_session]
                    )
        
                submit_btn.click(
                    respond,
                    [txt_message, chat_bot, app_session],
                    [txt_message,chat_bot, app_session]
                )

                clear_button.click(
                    clear,
                    [txt_message, app_session],
                    [txt_message, chat_bot, app_session]
                )

# launch
demo.launch(share=False, debug=True, show_api=False, server_port=7860, server_name="0.0.0.0")

**Comment by Note-Liu** [comment]
> mgr.Chatbot 应该是不支持 examples 的，有具体的代码示例吗


import gradio as gr
import io
import os
import copy

import modelscope_studio as mgr
from io import BytesIO

model_name = "Test"
ERROR_MSG = "Error, please retry"

def respond(_question, _chat_bot, _app_cfg):
    _answer = "床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。床前明月光，疑是地上霜。举头望明月，低头思故乡。"
    _chat_bot.append((_question,_answer))
    
    return  gr.MultimodalTextbox(
            interactive=True,
            file_types=["image"],
            placeholder="Enter message or upload file...",
            show_label=False,
            file_count="multiple"
        ), _chat_bot, _app_cfg
  

def clear(txt_message, app_session):
    print("Clear")
    txt_message.clear()
    app_session['sts'] = None
    app_session['ctx'] = []
    new_chat_bot_value = []
    return gr.MultimodalTextbox(value=None, interactive=True), gr.Chatbot(value=new_chat_bot_value) , app_session


block_css = """
.gradio-container {margin: 0.1% 1% 0 1% !important; max-width: 98% !important;};
#buttons button {
    min-width: min(120px,100%);
}

.gradient-text {
    font-size: 28px;
    width: auto;
    font-weight: bold;
    background: linear-gradient(45deg, red, orange, yellow, green, blue, indigo, violet);
    background-clip: text;
    -webkit-background-clip: text;
    color: transparent;
}

.plain-text {
    font-size: 22px;
    width: auto;
    font-weight: bold;
}
"""
init_conversation = [
    [
        None,
        {
            "text": "Talk to me now",
            "flushing": False
        }
    ],
]

txt_message = gr.MultimodalTextbox(
    interactive=True,
    file_types=["image"],
    placeholder="Enter message ...",
    show_label=False,
    file_count="multiple"
)

with gr.Blocks(css=block_css) as demo: 
    with gr.Tab(model_name):  
        with gr.Row():
            # 左侧列内容
            with gr.Column(scale=2):
                examples = gr.Examples(
                    examples=[
                            [{"files": ["data/001.png"], "text":"描述一下图片"}],
                            [{"files": ["data/002.png"], "text": "描述一下图片"}],
                            [{"files": ["data/003.png"], "text": "描述一下图片"}],
                            [{"files": ["data/004.png"], "text": "描述一下图片"}],
                            ],
                    inputs=[txt_message]
                    )

            with gr.Column(scale = 8):
                app_session = gr.State({'sts': None, 'ctx': [], 'images_cnt': 0, 'chat_type': 'Chat'}) 
                 
                chat_bot =  mgr.Chatbot(label=f"Chat with {model_name}", value=copy.deepcopy(init_conversation), height=600, flushing=False, bubble_full_width=False)
                 
                with gr.Row():
                    with gr.Column(scale=8):
                        txt_message.render()
                    submit_btn = gr.Button(value="Submit", variant="primary")
                    clear_button = gr.Button(value='Clear', interactive=True)
                    
                    txt_message.submit(
                        respond,
                        [txt_message, chat_bot, app_session],
                        [txt_message, chat_bot, app_session]
                    )
        
                submit_btn.click(
                    respond,
                    [txt_message, chat_bot, app_session],
                    [txt_message,chat_bot, app_session]
                )

                clear_button.click(
                    clear,
                    [txt_message, app_session],
                    [txt_message, chat_bot, app_session]
                )

# launch
demo.launch(share=False, debug=True, show_api=False, server_port=7860, server_name="0.0.0.0")

**Comment by Note-Liu** [comment]
> mgr.Chatbot 应该是不支持 examples 的，有具体的代码示例吗

[test.zip](https://github.com/user-attachments/files/18273812/test.zip)

**Comment by Col0ring** [comment]
> > mgr.Chatbot 应该是不支持 examples 的，有具体的代码示例吗
> 
> [test.zip](https://github.com/user-attachments/files/18273812/test.zip)

我这边使用最新的`modelscope_studio`版本是正常的，你可以下载最新版试试，可以看下 README 里面的迁移指南。

**Comment by Note-Liu** [comment]
> > > mgr.Chatbot 应该是不支持 examples 的，有具体的代码示例吗
> > 
> > 
> > [test.zip](https://github.com/user-attachments/files/18273812/test.zip)
> 
> 我这边使用最新的`modelscope_studio`版本是正常的，你可以下载最新版试试，可以看下 README 里面的迁移指南。

Thx!
