### ISSUE TITLE
markdown bug，在accordion内的markdown无法正常渲染，官方demo也无法正常渲染

### ISSUE THREAD

**Issue by chenchenchen7** [modelscope/modelscope-studio#9]
![image](https://github.com/modelscope/modelscope-studio/assets/38950233/76976a0b-6337-493a-bebb-7dbb38fe62f7)
![image](https://github.com/modelscope/modelscope-studio/assets/38950233/6ce2e942-ff93-4860-a5f8-46d850538591)
好像只有qwen内置的模版可以，其他的有问题

**Comment by Col0ring** [comment]
感谢指出，自定义标签解析时上下需要额外空一行，官方 Demo 后续也会跟进修改：

````text
Use accordion tag:

<accordion title="Using tool">

```json
{{"text": "glorious weather", "resolution": "1024*1024"}}
```

</accordion>

````
